export const dataSource = [
    {
        key: '1',
        firstName: 'John',
        lastName: 'Doe',
        user_role: 'Admin',
        user_login: 'jdoe',
        user_password: 'jdoe1234',
    },
    {
        key: '2',
        firstName: 'Jane',
        lastName: 'Smith',
        user_role: 'YHXB',
        user_login: 'jsmith',
        user_password: 'jsmith5678',
    },
    {
        key: '3',
        firstName: 'Emily',
        lastName: 'Johnson',
        user_role: 'Service',
        user_login: 'ejohnson',
        user_password: 'ejohnson4321',
    },
    {
        key: '4',
        firstName: 'Michael',
        lastName: 'Brown',
        user_role: 'Admin',
        user_login: 'mbrown',
        user_password: 'mbrown8765',
    },
    {
        key: '5',
        firstName: 'Sarah',
        lastName: 'Davis',
        user_role: 'Service',
        user_login: 'sdavis',
        user_password: 'sdavis9101',
    },
    {
        key: '6',
        firstName: 'David',
        lastName: 'Wilson',
        user_role: 'YIDXP',
        user_login: 'dwilson',
        user_password: 'dwilson538',
    },
    {
        key: '7',
        firstName: 'Laura',
        lastName: 'Moore',
        user_role: 'Admin',
        user_login: 'lmoore',
        user_password: 'lmoore438',
    },
    {
        key: '8',
        firstName: 'James',
        lastName: 'Taylor',
        user_role: 'YHXB',
        user_login: 'jtaylor',
        user_password: 'jtaylor984',
    },
    {
        key: '9',
        firstName: 'Olivia',
        lastName: 'Anderson',
        user_role: 'YIDXP',
        user_login: 'oanderson',
        user_password: 'oanderson238',
    },
    {
        key: '10',
        firstName: 'Daniel',
        lastName: 'Thomas',
        user_role: 'YHXB',
        user_login: 'dthomas',
        user_password: 'dhthomas56',
    },
];