DROP TABLE IF EXISTS fines CASCADE;

DROP TABLE IF EXISTS driver_licences CASCADE;

DROP TABLE IF EXISTS car_services CASCADE;

DROP TABLE IF EXISTS services CASCADE;

DROP TABLE IF EXISTS car_types CASCADE;

DROP TABLE IF EXISTS cars CASCADE;

DROP TABLE IF EXISTS service_types CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS roles CASCADE;

DROP TYPE IF EXISTS is_admin_enum CASCADE;

DROP TYPE IF EXISTS categories CASCADE;

DROP TYPE IF EXISTS fine_status CASCADE;
