// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: car_service.proto

package mobile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CarServiceService_Create_FullMethodName  = "/mobile.CarServiceService/Create"
	CarServiceService_GetById_FullMethodName = "/mobile.CarServiceService/GetById"
	CarServiceService_GetAll_FullMethodName  = "/mobile.CarServiceService/GetAll"
	CarServiceService_Delete_FullMethodName  = "/mobile.CarServiceService/Delete"
)

// CarServiceServiceClient is the client API for CarServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarServiceServiceClient interface {
	Create(ctx context.Context, in *CarServiceCreateReq, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*CarServiceGetByIdRes, error)
	GetAll(ctx context.Context, in *CarServiceGetAllReq, opts ...grpc.CallOption) (*CarServiceGetAllRes, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type carServiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarServiceServiceClient(cc grpc.ClientConnInterface) CarServiceServiceClient {
	return &carServiceServiceClient{cc}
}

func (c *carServiceServiceClient) Create(ctx context.Context, in *CarServiceCreateReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, CarServiceService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*CarServiceGetByIdRes, error) {
	out := new(CarServiceGetByIdRes)
	err := c.cc.Invoke(ctx, CarServiceService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceServiceClient) GetAll(ctx context.Context, in *CarServiceGetAllReq, opts ...grpc.CallOption) (*CarServiceGetAllRes, error) {
	out := new(CarServiceGetAllRes)
	err := c.cc.Invoke(ctx, CarServiceService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carServiceServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, CarServiceService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarServiceServiceServer is the server API for CarServiceService service.
// All implementations must embed UnimplementedCarServiceServiceServer
// for forward compatibility
type CarServiceServiceServer interface {
	Create(context.Context, *CarServiceCreateReq) (*Void, error)
	GetById(context.Context, *ById) (*CarServiceGetByIdRes, error)
	GetAll(context.Context, *CarServiceGetAllReq) (*CarServiceGetAllRes, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedCarServiceServiceServer()
}

// UnimplementedCarServiceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCarServiceServiceServer struct {
}

func (UnimplementedCarServiceServiceServer) Create(context.Context, *CarServiceCreateReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCarServiceServiceServer) GetById(context.Context, *ById) (*CarServiceGetByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCarServiceServiceServer) GetAll(context.Context, *CarServiceGetAllReq) (*CarServiceGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCarServiceServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCarServiceServiceServer) mustEmbedUnimplementedCarServiceServiceServer() {}

// UnsafeCarServiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarServiceServiceServer will
// result in compilation errors.
type UnsafeCarServiceServiceServer interface {
	mustEmbedUnimplementedCarServiceServiceServer()
}

func RegisterCarServiceServiceServer(s grpc.ServiceRegistrar, srv CarServiceServiceServer) {
	s.RegisterService(&CarServiceService_ServiceDesc, srv)
}

func _CarServiceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarServiceCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarServiceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServiceServer).Create(ctx, req.(*CarServiceCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarServiceService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarServiceService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarServiceService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarServiceGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarServiceService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServiceServer).GetAll(ctx, req.(*CarServiceGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarServiceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarServiceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarServiceService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarServiceServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// CarServiceService_ServiceDesc is the grpc.ServiceDesc for CarServiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarServiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mobile.CarServiceService",
	HandlerType: (*CarServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CarServiceService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CarServiceService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CarServiceService_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CarServiceService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car_service.proto",
}
