// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: car_type.proto

package mobile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CarTypeService_Create_FullMethodName  = "/mobile.CarTypeService/Create"
	CarTypeService_GetById_FullMethodName = "/mobile.CarTypeService/GetById"
	CarTypeService_GetAll_FullMethodName  = "/mobile.CarTypeService/GetAll"
	CarTypeService_Delete_FullMethodName  = "/mobile.CarTypeService/Delete"
)

// CarTypeServiceClient is the client API for CarTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarTypeServiceClient interface {
	Create(ctx context.Context, in *CarTypeCreateReq, opts ...grpc.CallOption) (*Void, error)
	GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*CarTypeGetByIdRes, error)
	GetAll(ctx context.Context, in *CarTypeGetAllReq, opts ...grpc.CallOption) (*CarTypeGetAllRes, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
}

type carTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCarTypeServiceClient(cc grpc.ClientConnInterface) CarTypeServiceClient {
	return &carTypeServiceClient{cc}
}

func (c *carTypeServiceClient) Create(ctx context.Context, in *CarTypeCreateReq, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, CarTypeService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carTypeServiceClient) GetById(ctx context.Context, in *ById, opts ...grpc.CallOption) (*CarTypeGetByIdRes, error) {
	out := new(CarTypeGetByIdRes)
	err := c.cc.Invoke(ctx, CarTypeService_GetById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carTypeServiceClient) GetAll(ctx context.Context, in *CarTypeGetAllReq, opts ...grpc.CallOption) (*CarTypeGetAllRes, error) {
	out := new(CarTypeGetAllRes)
	err := c.cc.Invoke(ctx, CarTypeService_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carTypeServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, CarTypeService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarTypeServiceServer is the server API for CarTypeService service.
// All implementations must embed UnimplementedCarTypeServiceServer
// for forward compatibility
type CarTypeServiceServer interface {
	Create(context.Context, *CarTypeCreateReq) (*Void, error)
	GetById(context.Context, *ById) (*CarTypeGetByIdRes, error)
	GetAll(context.Context, *CarTypeGetAllReq) (*CarTypeGetAllRes, error)
	Delete(context.Context, *ById) (*Void, error)
	mustEmbedUnimplementedCarTypeServiceServer()
}

// UnimplementedCarTypeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCarTypeServiceServer struct {
}

func (UnimplementedCarTypeServiceServer) Create(context.Context, *CarTypeCreateReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCarTypeServiceServer) GetById(context.Context, *ById) (*CarTypeGetByIdRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedCarTypeServiceServer) GetAll(context.Context, *CarTypeGetAllReq) (*CarTypeGetAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCarTypeServiceServer) Delete(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCarTypeServiceServer) mustEmbedUnimplementedCarTypeServiceServer() {}

// UnsafeCarTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarTypeServiceServer will
// result in compilation errors.
type UnsafeCarTypeServiceServer interface {
	mustEmbedUnimplementedCarTypeServiceServer()
}

func RegisterCarTypeServiceServer(s grpc.ServiceRegistrar, srv CarTypeServiceServer) {
	s.RegisterService(&CarTypeService_ServiceDesc, srv)
}

func _CarTypeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarTypeCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarTypeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarTypeService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarTypeServiceServer).Create(ctx, req.(*CarTypeCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarTypeService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarTypeServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarTypeService_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarTypeServiceServer).GetById(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarTypeService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarTypeGetAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarTypeServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarTypeService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarTypeServiceServer).GetAll(ctx, req.(*CarTypeGetAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarTypeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarTypeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarTypeService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarTypeServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

// CarTypeService_ServiceDesc is the grpc.ServiceDesc for CarTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mobile.CarTypeService",
	HandlerType: (*CarTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CarTypeService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _CarTypeService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CarTypeService_GetAll_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CarTypeService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "car_type.proto",
}
