// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: service_type.proto

package mobile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceTypeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceTypeRes) Reset() {
	*x = ServiceTypeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTypeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeRes) ProtoMessage() {}

func (x *ServiceTypeRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeRes.ProtoReflect.Descriptor instead.
func (*ServiceTypeRes) Descriptor() ([]byte, []int) {
	return file_service_type_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceTypeRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceTypeRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceTypeCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ServiceTypeCreateReq) Reset() {
	*x = ServiceTypeCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTypeCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeCreateReq) ProtoMessage() {}

func (x *ServiceTypeCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeCreateReq.ProtoReflect.Descriptor instead.
func (*ServiceTypeCreateReq) Descriptor() ([]byte, []int) {
	return file_service_type_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceTypeCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceTypeGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service *ServiceTypeRes `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *ServiceTypeGetByIdRes) Reset() {
	*x = ServiceTypeGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTypeGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeGetByIdRes) ProtoMessage() {}

func (x *ServiceTypeGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeGetByIdRes.ProtoReflect.Descriptor instead.
func (*ServiceTypeGetByIdRes) Descriptor() ([]byte, []int) {
	return file_service_type_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceTypeGetByIdRes) GetService() *ServiceTypeRes {
	if x != nil {
		return x.Service
	}
	return nil
}

type ServiceTypeGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*ServiceTypeRes `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ServiceTypeGetAllRes) Reset() {
	*x = ServiceTypeGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTypeGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeGetAllRes) ProtoMessage() {}

func (x *ServiceTypeGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_service_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeGetAllRes.ProtoReflect.Descriptor instead.
func (*ServiceTypeGetAllRes) Descriptor() ([]byte, []int) {
	return file_service_type_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceTypeGetAllRes) GetServices() []*ServiceTypeRes {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceTypeGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ServiceTypeGetAllReq) Reset() {
	*x = ServiceTypeGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceTypeGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTypeGetAllReq) ProtoMessage() {}

func (x *ServiceTypeGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTypeGetAllReq.ProtoReflect.Descriptor instead.
func (*ServiceTypeGetAllReq) Descriptor() ([]byte, []int) {
	return file_service_type_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceTypeGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_service_type_proto protoreflect.FileDescriptor

var file_service_type_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x1a, 0x0d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x49, 0x0a,
	0x15, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x4a, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x12, 0x32, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x22, 0x3e, 0x0a, 0x14, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x32, 0xee, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0c, 0x2e, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x1d, 0x2e, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x12, 0x1c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x1c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12,
	0x24, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_type_proto_rawDescOnce sync.Once
	file_service_type_proto_rawDescData = file_service_type_proto_rawDesc
)

func file_service_type_proto_rawDescGZIP() []byte {
	file_service_type_proto_rawDescOnce.Do(func() {
		file_service_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_type_proto_rawDescData)
	})
	return file_service_type_proto_rawDescData
}

var file_service_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_service_type_proto_goTypes = []interface{}{
	(*ServiceTypeRes)(nil),        // 0: mobile.ServiceTypeRes
	(*ServiceTypeCreateReq)(nil),  // 1: mobile.ServiceTypeCreateReq
	(*ServiceTypeGetByIdRes)(nil), // 2: mobile.ServiceTypeGetByIdRes
	(*ServiceTypeGetAllRes)(nil),  // 3: mobile.ServiceTypeGetAllRes
	(*ServiceTypeGetAllReq)(nil),  // 4: mobile.ServiceTypeGetAllReq
	(*Filter)(nil),                // 5: mobile.Filter
	(*ById)(nil),                  // 6: mobile.ById
	(*Void)(nil),                  // 7: mobile.Void
}
var file_service_type_proto_depIdxs = []int32{
	0, // 0: mobile.ServiceTypeGetByIdRes.service:type_name -> mobile.ServiceTypeRes
	0, // 1: mobile.ServiceTypeGetAllRes.services:type_name -> mobile.ServiceTypeRes
	5, // 2: mobile.ServiceTypeGetAllReq.filter:type_name -> mobile.Filter
	1, // 3: mobile.ServiceTypeService.Create:input_type -> mobile.ServiceTypeCreateReq
	6, // 4: mobile.ServiceTypeService.GetById:input_type -> mobile.ById
	4, // 5: mobile.ServiceTypeService.GetAll:input_type -> mobile.ServiceTypeGetAllReq
	6, // 6: mobile.ServiceTypeService.Delete:input_type -> mobile.ById
	7, // 7: mobile.ServiceTypeService.Create:output_type -> mobile.Void
	2, // 8: mobile.ServiceTypeService.GetById:output_type -> mobile.ServiceTypeGetByIdRes
	3, // 9: mobile.ServiceTypeService.GetAll:output_type -> mobile.ServiceTypeGetAllRes
	7, // 10: mobile.ServiceTypeService.Delete:output_type -> mobile.Void
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_type_proto_init() }
func file_service_type_proto_init() {
	if File_service_type_proto != nil {
		return
	}
	file_common2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTypeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTypeCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTypeGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTypeGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceTypeGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_type_proto_goTypes,
		DependencyIndexes: file_service_type_proto_depIdxs,
		MessageInfos:      file_service_type_proto_msgTypes,
	}.Build()
	File_service_type_proto = out.File
	file_service_type_proto_rawDesc = nil
	file_service_type_proto_goTypes = nil
	file_service_type_proto_depIdxs = nil
}
