// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: car_service.proto

package mobile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CarNumber   string          `protobuf:"bytes,2,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	ServiceType *ServiceTypeRes `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceDate string          `protobuf:"bytes,4,opt,name=service_date,json=serviceDate,proto3" json:"service_date,omitempty"`
	ExpDate     string          `protobuf:"bytes,5,opt,name=exp_date,json=expDate,proto3" json:"exp_date,omitempty"`
}

func (x *CarServiceRes) Reset() {
	*x = CarServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarServiceRes) ProtoMessage() {}

func (x *CarServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_car_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarServiceRes.ProtoReflect.Descriptor instead.
func (*CarServiceRes) Descriptor() ([]byte, []int) {
	return file_car_service_proto_rawDescGZIP(), []int{0}
}

func (x *CarServiceRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CarServiceRes) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *CarServiceRes) GetServiceType() *ServiceTypeRes {
	if x != nil {
		return x.ServiceType
	}
	return nil
}

func (x *CarServiceRes) GetServiceDate() string {
	if x != nil {
		return x.ServiceDate
	}
	return ""
}

func (x *CarServiceRes) GetExpDate() string {
	if x != nil {
		return x.ExpDate
	}
	return ""
}

type CarServiceCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarNumber   string `protobuf:"bytes,1,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	ServiceType string `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	ServiceDate string `protobuf:"bytes,3,opt,name=service_date,json=serviceDate,proto3" json:"service_date,omitempty"`
	ExpDate     string `protobuf:"bytes,4,opt,name=exp_date,json=expDate,proto3" json:"exp_date,omitempty"`
}

func (x *CarServiceCreateReq) Reset() {
	*x = CarServiceCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarServiceCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarServiceCreateReq) ProtoMessage() {}

func (x *CarServiceCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_car_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarServiceCreateReq.ProtoReflect.Descriptor instead.
func (*CarServiceCreateReq) Descriptor() ([]byte, []int) {
	return file_car_service_proto_rawDescGZIP(), []int{1}
}

func (x *CarServiceCreateReq) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *CarServiceCreateReq) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *CarServiceCreateReq) GetServiceDate() string {
	if x != nil {
		return x.ServiceDate
	}
	return ""
}

func (x *CarServiceCreateReq) GetExpDate() string {
	if x != nil {
		return x.ExpDate
	}
	return ""
}

type CarServiceGetByIdRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car *CarServiceRes `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
}

func (x *CarServiceGetByIdRes) Reset() {
	*x = CarServiceGetByIdRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarServiceGetByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarServiceGetByIdRes) ProtoMessage() {}

func (x *CarServiceGetByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_car_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarServiceGetByIdRes.ProtoReflect.Descriptor instead.
func (*CarServiceGetByIdRes) Descriptor() ([]byte, []int) {
	return file_car_service_proto_rawDescGZIP(), []int{2}
}

func (x *CarServiceGetByIdRes) GetCar() *CarServiceRes {
	if x != nil {
		return x.Car
	}
	return nil
}

type CarServiceGetAllRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars []*CarServiceRes `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
}

func (x *CarServiceGetAllRes) Reset() {
	*x = CarServiceGetAllRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarServiceGetAllRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarServiceGetAllRes) ProtoMessage() {}

func (x *CarServiceGetAllRes) ProtoReflect() protoreflect.Message {
	mi := &file_car_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarServiceGetAllRes.ProtoReflect.Descriptor instead.
func (*CarServiceGetAllRes) Descriptor() ([]byte, []int) {
	return file_car_service_proto_rawDescGZIP(), []int{3}
}

func (x *CarServiceGetAllRes) GetCars() []*CarServiceRes {
	if x != nil {
		return x.Cars
	}
	return nil
}

type CarServiceGetAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarNumber   string  `protobuf:"bytes,1,opt,name=car_number,json=carNumber,proto3" json:"car_number,omitempty"`
	ServiceType string  `protobuf:"bytes,2,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Filter      *Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *CarServiceGetAllReq) Reset() {
	*x = CarServiceGetAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_car_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarServiceGetAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarServiceGetAllReq) ProtoMessage() {}

func (x *CarServiceGetAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_car_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarServiceGetAllReq.ProtoReflect.Descriptor instead.
func (*CarServiceGetAllReq) Descriptor() ([]byte, []int) {
	return file_car_service_proto_rawDescGZIP(), []int{4}
}

func (x *CarServiceGetAllReq) GetCarNumber() string {
	if x != nil {
		return x.CarNumber
	}
	return ""
}

func (x *CarServiceGetAllReq) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *CarServiceGetAllReq) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_car_service_proto protoreflect.FileDescriptor

var file_car_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x1a, 0x0d, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7,
	0x01, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x39, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x52, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x65, 0x78, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x78, 0x70, 0x44, 0x61, 0x74, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x70, 0x44, 0x61, 0x74, 0x65,
	0x22, 0x3f, 0x0a, 0x14, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x43,
	0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x52, 0x03, 0x63, 0x61,
	0x72, 0x22, 0x40, 0x0a, 0x13, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e,
	0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x52, 0x04, 0x63,
	0x61, 0x72, 0x73, 0x22, 0x7f, 0x0a, 0x13, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61,
	0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x61, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x32, 0xe9, 0x01, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x61,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12,
	0x35, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x1c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c,
	0x65, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x12, 0x1b, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x42, 0x79,
	0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x42, 0x11, 0x5a, 0x0f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_car_service_proto_rawDescOnce sync.Once
	file_car_service_proto_rawDescData = file_car_service_proto_rawDesc
)

func file_car_service_proto_rawDescGZIP() []byte {
	file_car_service_proto_rawDescOnce.Do(func() {
		file_car_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_car_service_proto_rawDescData)
	})
	return file_car_service_proto_rawDescData
}

var file_car_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_car_service_proto_goTypes = []interface{}{
	(*CarServiceRes)(nil),        // 0: mobile.CarServiceRes
	(*CarServiceCreateReq)(nil),  // 1: mobile.CarServiceCreateReq
	(*CarServiceGetByIdRes)(nil), // 2: mobile.CarServiceGetByIdRes
	(*CarServiceGetAllRes)(nil),  // 3: mobile.CarServiceGetAllRes
	(*CarServiceGetAllReq)(nil),  // 4: mobile.CarServiceGetAllReq
	(*ServiceTypeRes)(nil),       // 5: mobile.ServiceTypeRes
	(*Filter)(nil),               // 6: mobile.Filter
	(*ById)(nil),                 // 7: mobile.ById
	(*Void)(nil),                 // 8: mobile.Void
}
var file_car_service_proto_depIdxs = []int32{
	5, // 0: mobile.CarServiceRes.service_type:type_name -> mobile.ServiceTypeRes
	0, // 1: mobile.CarServiceGetByIdRes.car:type_name -> mobile.CarServiceRes
	0, // 2: mobile.CarServiceGetAllRes.cars:type_name -> mobile.CarServiceRes
	6, // 3: mobile.CarServiceGetAllReq.filter:type_name -> mobile.Filter
	1, // 4: mobile.CarServiceService.Create:input_type -> mobile.CarServiceCreateReq
	7, // 5: mobile.CarServiceService.GetById:input_type -> mobile.ById
	4, // 6: mobile.CarServiceService.GetAll:input_type -> mobile.CarServiceGetAllReq
	7, // 7: mobile.CarServiceService.Delete:input_type -> mobile.ById
	8, // 8: mobile.CarServiceService.Create:output_type -> mobile.Void
	2, // 9: mobile.CarServiceService.GetById:output_type -> mobile.CarServiceGetByIdRes
	3, // 10: mobile.CarServiceService.GetAll:output_type -> mobile.CarServiceGetAllRes
	8, // 11: mobile.CarServiceService.Delete:output_type -> mobile.Void
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_car_service_proto_init() }
func file_car_service_proto_init() {
	if File_car_service_proto != nil {
		return
	}
	file_common2_proto_init()
	file_service_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_car_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarServiceCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarServiceGetByIdRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarServiceGetAllRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_car_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarServiceGetAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_car_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_service_proto_goTypes,
		DependencyIndexes: file_car_service_proto_depIdxs,
		MessageInfos:      file_car_service_proto_msgTypes,
	}.Build()
	File_car_service_proto = out.File
	file_car_service_proto_rawDesc = nil
	file_car_service_proto_goTypes = nil
	file_car_service_proto_depIdxs = nil
}
